# This is a Makefile for `cargo make`, to use it first istall cargo-make with `cargo install cargo-make`

[config]
skip_core_tasks = true

[config.modify_core_tasks]
# if true, all core tasks are set to private (default false)
private = true

## Feature profiles
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
TDNS_WITH_KCOV_ARGS = "--bins --tests --examples"

# TODO: add --lib back when there is a common cli library in bin
#  probably just remove this override file at that point

[tasks.check]
command = "cargo"
args = ["check", "--examples", "--tests", "--bins", "@@remove-empty(FEATURES)"]

[tasks.build]
command = "cargo"
args = ["build", "--bins",  "@@remove-empty(FEATURES)"]

[tasks.test]
command = "cargo"
dependencies = []
args = ["test", "--examples", "--tests", "--bins", "@@remove-empty(FEATURES)"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--examples", "--tests", "--bins", "@@remove-empty(FEATURES)", "--", "-D", "warnings"]
