clone_depth: 1

environment:
  matrix:
  - DEFAULT_SUITE: 1
    TARGET: x86_64-pc-windows-msvc
    BITS: 64
    OPENSSL_VERSION: 1_1_0h
    OPENSSL_DIR: C:\OpenSSL

  - ALL_FEATURES_SUITE: 1
    TARGET: x86_64-pc-windows-msvc
    BITS: 64
    OPENSSL_VERSION: 1_1_0h
    OPENSSL_DIR: C:\OpenSSL

  - NO_DEFAULT_FEATURES_SUITE: 1
    TARGET: x86_64-pc-windows-msvc
    BITS: 64
    OPENSSL_VERSION: 1_1_0h
    OPENSSL_DIR: C:\OpenSSL

  - DNSSEC_OPENSSL_SUITE: 1
    TARGET: x86_64-pc-windows-msvc
    BITS: 64
    OPENSSL_VERSION: 1_1_0h
    OPENSSL_DIR: C:\OpenSSL

  - DNSSEC_RING_SUITE: 1
    TARGET: x86_64-pc-windows-msvc
    BITS: 64
    OPENSSL_VERSION: 1_1_0h
    OPENSSL_DIR: C:\OpenSSL

  - DNS_OVER_TLS_SUITE: 1
    TARGET: x86_64-pc-windows-msvc
    BITS: 64
    OPENSSL_VERSION: 1_1_0h
    OPENSSL_DIR: C:\OpenSSL

  # Just checking the basics on i686/32bit
  - TARGET: i686-pc-windows-msvc
    ALL_FEATURES_SUITE: 1
    BITS: 32
    OPENSSL_VERSION: 1_1_0h
    OPENSSL_DIR: C:\OpenSSL

init:
  - ps: Disable-NetFirewallRule -DisplayName 'Core Networking - Group Policy (LSASS-Out)'

install:
  # Install OpenSSL
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-${env:OPENSSL_VERSION}.exe"
  - Win%BITS%OpenSSL-%OPENSSL_VERSION%.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: Start-FileDownload "https://curl.haxx.se/ca/cacert.pem" -FileName "C:\OpenSSL\cacert.pem"

  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

# All grouped by feature to reduce recompilation of the libraries
test_script:
  - scripts\test_windows.bat
