[package]
name = "trust-dns"
version = "0.5.3"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

# A short blurb about the package. This is not rendered in any format when
# uploaded to crates.io (aka this is not markdown)
description = """\
TRust-DNS is a safe and secure DNS server and client with DNSec support.\
 It is working to be a replacement for BIND9. DNSSec on the client side, with\
 NSEC validation for negative records, is complete. The client and server both\
 support dynamic DNS, SIG0 and TSIG validation are currently a WIP. Full DNSSec\
 on the server is a WIP.\
"""

# These URLs point to more information about the repository
documentation = "http://www.trust-dns.org/target/doc/trust_dns/index.html"
homepage = "http://www.trust-dns.org/index.html"
repository = "https://github.com/bluejekyll/trust-dns"

# This points to a file in the repository (relative to this Cargo.toml). The
# contents of this file are stored and indexed in the registry.
readme = "README.md"

# This is a small list of keywords used to categorize and search for this
# package.
keywords = ["DNS", "BIND", "dig", "named", "dnssec"]

# This is a string description of the license for this package. Currently
# crates.io will validate the license provided against a whitelist of known
# license identifiers from http://spdx.org/licenses/. Multiple licenses can
# be separated with a `/`
license = "MIT OR Apache-2.0"

# custom build steps
build = "build.rs"

[features]
# run functional tests with tests
ftest = []


[lib]
name = "trust_dns"
path = "src/lib.rs"

[[bin]]
name = "named"
path = "src/named.rs"


[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
rpath = false  # Controls whether the compiler passes `-C rpath`
lto = false    # Controls `-C lto` for binaries and staticlibs
debug-assertions = true  # Controls whether debug assertions are enabled
codegen-units = 1 # Controls whether the compiler passes `-C codegen-units`
                  # `codegen-units` is ignored when `lto = true`

# The testing profile, used for `cargo test`
[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1

[dependencies]
chrono = "^0.2.21"
data-encoding = "^1.1.2"
docopt = "^0.6.78"
log = "^0.3.5"
mio = "^0.5.1"
openssl = "^0.7.8"
openssl-sys = "^0.7.8"
rustc-serialize = "^0.3.18"
toml = "^0.1.28"
