[workspace]
members = ["crates/proto",
           "crates/native-tls",
           "crates/openssl",
           "crates/rustls",
           "crates/https",
           "crates/resolver",
           "crates/client", 
           "crates/server",
           "crates/async-std-resolver",
           "bin",
           "util",
           "tests/compatibility-tests",
           "tests/integration-tests"]
