[workspace]
members = [
    "crates/proto",
    "crates/resolver",
    "crates/recursor",
    "crates/client", 
    "crates/server",
    "crates/async-std-resolver",
    "bin",
    "util",
    "tests/compatibility-tests",
    "tests/integration-tests",
]

exclude = [
    "fuzz",
]

[patch.crates-io]
# tokio = { path = "../tokio/tokio" }
# mio = { git = "https://github.com/tokio-rs/mio.git" }
# h2 = { git = "https://github.com/hyperium/h2.git" }
