[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "dns-test"
publish = false
version = "0.1.0"

[dependencies]
base64 = "0.22.1"
hex = "0.4.3"
lazy_static = "1.4.0"
minijinja = "2"
rcgen = "0.14"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_with = "3.6.1"
tempfile = "3.9.0"
url = "2.5.0"

[lib]
doctest = false

[dev-dependencies]
ctrlc = "3.4.2"
pretty_assertions = "1.4.0"
