[package]
name = "trust-dns-util"
version = "0.22.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]
edition = "2018"

# A short blurb about the package. This is not rendered in any format when
# uploaded to crates.io (aka this is not markdown)
description = """
Utilities that complement Trust-DNS.
"""

# These URLs point to more information about the repository
documentation = "https://docs.rs/crate/trust-dns-util"
homepage = "http://www.trust-dns.org/index.html"
repository = "https://github.com/bluejekyll/trust-dns"

# This points to a file in the repository (relative to this Cargo.toml). The
# contents of this file are stored and indexed in the registry.
readme = "README.md"

# This is a small list of keywords used to categorize and search for this
# package.
keywords = ["DNS", "BIND", "dig", "named", "dnssec"]
categories = ["network-programming"]

# This is a string description of the license for this package. Currently
# crates.io will validate the license provided against a whitelist of known
# license identifiers from http://spdx.org/licenses/. Multiple licenses can
# be separated with a `/`
license = "MIT/Apache-2.0"

[badges]
#github-actions = { repository = "bluejekyll/trust-dns", branch = "main", workflow = "test" }
codecov = { repository = "bluejekyll/trust-dns", branch = "main", service = "github" }
maintenance = { status = "actively-developed" }

[features]
dns-over-rustls = ["rustls", "webpki", "webpki-roots", "trust-dns-proto/dns-over-rustls", "trust-dns-client/dns-over-rustls", "trust-dns-resolver/dns-over-rustls"]
dns-over-https-rustls = ["dns-over-https", "dns-over-rustls", "trust-dns-proto/dns-over-https-rustls", "trust-dns-client/dns-over-https-rustls", "trust-dns-resolver/dns-over-https-rustls"]
dns-over-https = ["trust-dns-proto/dns-over-https", "trust-dns-client/dns-over-https","trust-dns-resolver/dns-over-https"]

dns-over-quic = ["dns-over-rustls", "trust-dns-resolver/dns-over-quic"]

dnssec = []
dnssec-openssl = ["dnssec", "openssl", "trust-dns-client/dnssec-openssl", "trust-dns-proto/dnssec-openssl", "trust-dns-resolver/dnssec-openssl"]
dnssec-ring = ["dnssec", "trust-dns-client/dnssec-ring", "trust-dns-proto/dnssec-ring", "trust-dns-resolver/dnssec-ring"]

[[bin]]
name = "dns"
path = "src/dns.rs"

[[bin]]
name = "dnskey-to-pem"
path = "src/bind_dnskey_to_pem.rs"
required-features = ["dnssec-openssl"]

[[bin]]
name = "get-root-ksks"
path = "src/get_root_ksks.rs"
required-features = ["dnssec-openssl"]

[[bin]]
name = "pem-to-public-dnskey"
path = "src/pem_to_public_dnskey.rs"
required-features = ["dnssec-openssl"]

[[bin]]
name = "resolve"
path = "src/resolve.rs"

[[bin]]
name = "recurse"
path = "src/recurse.rs"

[dependencies]
clap = { version = "3.1", default-features = false, features = ["std", "cargo", "derive", "color", "suggestions"] }
console = "0.15.0"
data-encoding = "2.2.0"
openssl = { version = "0.10", features = ["v102", "v110"], optional = true }
rustls = { version = "0.20.0", features = ["dangerous_configuration"], optional = true }
tracing = "0.1.30"
tracing-subscriber = { version = "0.3", features = ["std", "fmt", "env-filter"] }
trust-dns-client = { version = "0.22.0", path = "../crates/client" }
trust-dns-proto = { version = "0.22.0", path = "../crates/proto" }
trust-dns-recursor = { version = "0.22.0", path = "../crates/recursor" }
trust-dns-resolver = { version = "0.22.0", path = "../crates/resolver" }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
webpki = { version = "0.22.0", optional = true }
webpki-roots = { version = "0.22.1", optional = true }

