[package]
name = "hickory-util"

# A short blurb about the package. This is not rendered in any format when
# uploaded to crates.io (aka this is not markdown)
description = """
Utilities that complement Hickory DNS.
"""

# These URLs point to more information about the repository
documentation = "https://docs.rs/crate/hickory-util"

# This points to a file in the repository (relative to this Cargo.toml). The
# contents of this file are stored and indexed in the registry.
readme = "README.md"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[badges]
#github-actions = { repository = "bluejekyll/hickory", branch = "main", workflow = "test" }
codecov = { repository = "hickory-dns/hickory-dns", branch = "main", service = "github" }
maintenance = { status = "actively-developed" }

[features]
dns-over-rustls = [
    "rustls",
    "hickory-proto/dns-over-rustls",
    "hickory-client/dns-over-rustls",
    "hickory-resolver/dns-over-rustls",
]
dns-over-https-rustls = [
    "dns-over-rustls",
    "hickory-proto/dns-over-https-rustls",
    "hickory-client/dns-over-https-rustls",
    "hickory-resolver/dns-over-https-rustls",
]
dns-over-quic = ["dns-over-rustls", "hickory-resolver/dns-over-quic"]
dns-over-h3 = ["dns-over-rustls", "hickory-resolver/dns-over-h3"]

webpki-roots = [
    "dep:webpki-roots",
    "hickory-proto/webpki-roots",
    "hickory-client/webpki-roots",
    "hickory-resolver/webpki-roots",
]
native-certs = [
    "dep:rustls-native-certs",
    "hickory-proto/native-certs",
    "hickory-client/native-certs",
    "hickory-resolver/native-certs",
]

dnssec = []
dnssec-ring = [
    "dnssec",
    "hickory-client/dnssec-ring",
    "hickory-proto/dnssec-ring",
    "hickory-resolver/dnssec-ring",
]

[dependencies]
clap = { workspace = true, default-features = false, features = [
    "std",
    "cargo",
    "derive",
    "color",
    "suggestions",
    "help",
    "usage",
] }
console.workspace = true
data-encoding.workspace = true
rustls = { workspace = true, optional = true }
rustls-native-certs = { workspace = true, optional = true }
tracing.workspace = true
tracing-subscriber. workspace = true
hickory-client.workspace = true
hickory-proto.workspace = true
hickory-recursor.workspace = true
hickory-resolver = { workspace = true, features = ["system-config"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
webpki-roots = { workspace = true, optional = true }

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
max_combination_size = 2
