[package]
name = "trust-dns-util"
version = "0.20.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]
edition = "2018"

# A short blurb about the package. This is not rendered in any format when
# uploaded to crates.io (aka this is not markdown)
description = """
Utilities that complement Trust-DNS.
"""

# These URLs point to more information about the repository
documentation = "https://docs.rs/crate/trust-dns-util"
homepage = "http://www.trust-dns.org/index.html"
repository = "https://github.com/bluejekyll/trust-dns"

# This points to a file in the repository (relative to this Cargo.toml). The
# contents of this file are stored and indexed in the registry.
readme = "README.md"

# This is a small list of keywords used to categorize and search for this
# package.
keywords = ["DNS", "BIND", "dig", "named", "dnssec"]
categories = ["network-programming"]

# This is a string description of the license for this package. Currently
# crates.io will validate the license provided against a whitelist of known
# license identifiers from http://spdx.org/licenses/. Multiple licenses can
# be separated with a `/`
license = "MIT/Apache-2.0"

[badges]
#github-actions = { repository = "bluejekyll/trust-dns", branch = "main", workflow = "test" }
codecov = { repository = "bluejekyll/trust-dns", branch = "main", service = "github" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "dnskey-to-pem"
path = "src/bind_dnskey_to_pem.rs"

[[bin]]
name = "get-root-ksks"
path = "src/get_root_ksks.rs"

[[bin]]
name = "pem-to-public-dnskey"
path = "src/pem_to_public_dnskey.rs"

[dependencies]
clap = "2.33.1"
data-encoding = "2.3.0"
trust-dns-client= { version = "0.20.0", features = ["dnssec-openssl"], path = "../crates/client" }
trust-dns-proto = { version = "0.20.0", features = ["dnssec-openssl"], path = "../crates/proto" }
trust-dns-resolver = { version = "0.20.0", features = ["dnssec-openssl"], path = "../crates/resolver" }
env_logger = "0.7"
log = "0.4"
openssl = { version = "0.10", features = ["v102", "v110"] }
