name: rust

on:
  push:
    branches:
      - cargo-make-automation
  pull_request:
    branches:
      - cargo-make-automation

jobs:
  cargo-make:
    name: install cargo-make
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: download and install cargo-make
      run: scripts/install-cargo-make.sh
